### PR TITLE
Upgrade to ruby 2.1.5

### PR DESCRIPTION
**Pull request by boonrs**
Addresses #219.

Uh, the tests pass, so surely that means the upgrade was a success.

### CODE REVIEW

**Comment by boonrs** [comment]
Doh! Travis file! Do you prefer squashing commits or you want this separate?

**Comment by daguar** [comment]
I'm fine with either — lemme know if you wanna squash (feel free to do) and I can merge. Thanks! :+1:

**Comment by boonrs** [comment]
Ok, squashed.

**Comment by daguar** [comment]
Sorry for falling down on this! Without support I haven't had time to act as a proper maintainer. Luckily with help from others this issue's now resolved so closing.

**Pull request closed without merging**
