### PR TITLE
Location URL Fixup

### PR DESCRIPTION
**Pull request by waltz**
I changed URLS on locations to take advantage of a little Rails URL routing magic. It simplifies some of the location lookup and handles funky characters like `'` and `\` a bit better in exchange for a crufty set of digits before the title.

### CODE REVIEW

**Comment by waltz** [comment]
Merged as 4e2ae78cc299b26ccdd8b98de9ad27a10ac61d28. Hooray!

**Comment by jmadans** [comment]
Oh shit. So this fixes #242?! @waltz

**Comment by waltz** [comment]
You betcha! I updated the test suite to cover this case, so this shouldn't be a problem in the future. :balloon:

**Comment by daguar** [comment]
Fuck yeah testing.

**Pull request closed without merging**
